version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    network_mode: "host" 
    restart: unless-stopped
    command: --prefix=/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/jenkins/login"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  jenkins_home:
