all:
  children:
    jenkins-master:
      hosts:
        192.168.56.11:
          # ansible_user: ansible
          # ansible_ssh_private_key_file: /home/reflection/.ssh/vagrant-ssh.pub ansible@192.168.56.11

