#SPDX-License-Identifier: MIT-0
---
# handlers file for jenkins-master

- name: reload nginx
  service:
    name: nginx
    state: reload
  become: true

- name: update_cache_docker
  apt:
    update_cache: yes
  become: true
  tags: install_docker

- name: restart_docker
  service:
    name: docker
    state: reloaded
  become: true
  tags: install_docker